version: '3.8'

services:
  db:
    image: mariadb:10.6
    container_name: wp_shop_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  wordpress:
    image: wordpress:latest
    container_name: wp_shop_app
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_password
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_CONFIG_EXTRA: |
        if (!defined('WP_HOME')) {
            $$host  = $$_SERVER['HTTP_HOST'] ?? 'localhost';
            $$proto = (!empty($$_SERVER['HTTPS']) && $$_SERVER['HTTPS'] !== 'off') ? 'https' : 'http';
            define('WP_HOME', $$proto . '://' . $$host);
            define('WP_SITEURL', $$proto . '://' . $$host);
        }

        define('WP_DEBUG', true);
        define('WP_DEBUG_LOG', true);
        define('WP_DEBUG_DISPLAY', false);
        @ini_set('log_errors', 1);
        @ini_set('display_errors', 0);
        define('WC_LOG_HANDLER', 'WC_Log_Handler_File');
        define('WC_LOG_LEVEL', 'debug');
    volumes:
      - wp-content:/var/www/html/wp-content
    networks:
      - app-network

  backend:
    build: 
      context: ./backend
      dockerfile: ./Dockerfile
    container_name: fastapi_backend
    restart: always
    volumes:
      - ./backend:/app # Монтуємо код для hot-reload під час розробки
    env_file:
      - .env
    networks:
      - app-network
    expose: 
      - "8000"

  agent:
    build:
      context: ./backend/sync-bot
      dockerfile: Dockerfile
    container_name: supplier_agent
    env_file:
      - .env
    volumes:
      - ./backend/sync-bot:/app
    depends_on:
      - backend
    networks:
      - app-network
    profiles:
      - manual
  
  frontend:
    image: node:20-slim
    container_name: react_frontend
    working_dir: /home/node/app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    expose: 
      - "5173"
    networks:
      - app-network
    volumes:  
      - ./frontend:/home/node/app
      - /home/node/app/node_modules


  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80" # Тільки цей порт відкритий назовні
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - webroot:/var/www/html
    depends_on:
      - wordpress
      - backend
      - frontend
    networks:
      - app-network
    restart: always
    
  certbot:
    image: certbot/certbot:latest
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - webroot:/var/www/html
    restart: always

volumes:
  db_data:
  wp_data:
  certbot-etc:
  certbot-var:
  webroot:
  wp-content:

networks:
  app-network:
    driver: bridge