server {

    listen 80;

    server_name localhost;


    location /api/ {

        proxy_pass http://fastapi_backend:8000;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        
        proxy_set_header Authorization $http_authorization;
        proxy_pass_request_headers on;
        proxy_set_header Cookie $http_cookie;
    }

    location ~ ^/(wp|wp-admin|wp-login\.php|wp-json|wp-content|wp-includes) {
        proxy_pass http://wp_shop_app;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }


    location / {
        proxy_pass http://react_frontend:5173;

        proxy_http_version 1.1;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}