resolver 127.0.0.11 valid=10s;

server {
    listen 80;
    server_name sunbeambe.com www.sunbeambe.com;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}



server {

    listen 443 ssl http2;

    server_name sunbeambe.com www.sunbeambe.com;

    ssl_certificate     /etc/letsencrypt/live/sunbeambe.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/sunbeambe.com/privkey.pem;

    location ~ ^/(wp|wp-admin|wp-login\.php|wp-json|wp-content|wp-includes) {
        set $wordpress_upstream wp_shop_app;
        proxy_pass http://$wordpress_upstream;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api{
        set $backend_upstream fastapi_backend;
        proxy_pass http://$backend_upstream:8000;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    location / {
        root /usr/share/nginx/html;
        try_files $uri /index.html;
    }
}